### ISSUE TITLE
Error retrieving Hauchiwa information

### ISSUE THREAD

**Issue by tvanhove** [tengu-team/tengu-browser#18]
Newly created streaming model, but an undescriptive error when retrieving the Hauchiwa information with the following command:
`:tengu hauchiwa status uxtest2`

**Comment by merlijn-sebrechts** [comment]
This is because a hook failed on the hauchiwa. See: https://github.com/IBCNServices/tengu-browser/issues/19

Failures in deployments of bundles (this case) will be better reported when we switch to async deployment of bundles. However it might be best if the UI could also at least show the error message if the Hauchiwa has a hook error.

**Comment by gvseghbr** [comment]
Hauchiwa level was removed.
