### ISSUE TITLE
Create new model on existing Hauchiwa

### ISSUE THREAD

**Issue by merlijn-sebrechts** [tengu-team/tengu-browser#3]
This includes the ability to select the model

The api call for this is present in the h_api: PUT to `/<modelname>/` will create a new model or update the model if it already exists.

**Comment by gvseghbr** [comment]
What would actually be the added value for a non-expert user?
I see an extra here for expert users and researchers. For example, create a Hauchiwa and on that Hauchiwa run a script that sets up many models for evaluation, benachmarking, ... purposes. And afterwards gather and aggregate results on the Hauchiwa. 
However, if you're using the web-ui to simply setup a model to try new things or whatever, from that user's perspective it will look the same if every model has its own Hauchiwa (it will even be easier for him to manage there model from the Hauchiwa).
If this issue is more about resource optimization, so a user will have a limited amount of Hauchiwas, perhaps we should simply enforce a one-Hauchiwa-per-user principle.

**Comment by merlijn-sebrechts** [comment]
I think we should make Hauchiwa's transparent for non-expert users. Non-expert users should only create models. What Hauchiwa the model is on shouldn't matter for them.

Aside from that, there are two advantages I can think of:
- Speed: Creating a Hauchiwa takes a while. This can become cumbersome during development and testing of Tengu. This is also something non-expert users will notice. The creation speed of a Hauchiwa will improve a lot when we publish or charms in the charm store.
- Resource usage: could be fixed by enforcing a limit on the Hauchiwa's although I think 1 is too small.

I myself would use this functionality a lot, the UI is an easy way for me to jump-start a model and the continue building on it using the CLI, but I want all my models to be accessible from my Hauchiwa. However, I can't be considered an expert user...

**Comment by merlijn-sebrechts** [comment]
After discussion and much thought: No, a non-expert user shouldn't do this, although it would be a nice-to-have for an expert user.

**Comment by gvseghbr** [comment]
I will add a button or link to the hauchiwa status page where you can add a model to that hauchiwa.
So an expert user should first go to its Hauchiwa `:tengu hauchiwa status {name}`. There he can see which models are available for the Hauchiwa and add an extra model to this Hauchiwa.

OK?

**Comment by merlijn-sebrechts** [comment]
Seems good to me!

2016-08-08 11:49 GMT+02:00 Gregory Van Seghbroeck notifications@github.com
:

**Comment by gvseghbr** [comment]
Hauchiwa level was removed.
